spring:
  application:
    name: media-settlement

  profiles:
    active: local
    include: oauth

  datasource:
    url: ${DATABASE_URL}
    username: root
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${RESIs_PORT:6379}
#      password: ${REDIS_PASSWORD:redispassword}